-- DROP DATABASE MANGA;
create database MANGA;

CREATE TABLE MANGA.UTILIDADE -- Tabela adicional UTILIDADE
(
ID INT PRIMARY KEY AUTO_INCREMENT,
 CAT VARCHAR (50) NOT NULL
);

INSERT INTO MANGA.UTILIDADE (CAT) VALUE ('ALIMENTACAO');
INSERT INTO MANGA.UTILIDADE (CAT) VALUE ('MEDICINAL');
INSERT INTO MANGA.UTILIDADE (CAT) VALUE ('COSMETICO');
INSERT INTO MANGA.UTILIDADE (CAT) VALUE ('DECORACAO');
INSERT INTO MANGA.UTILIDADE (CAT) VALUE ('INDUSTRIAL');

SELECT * FROM MANGA.UTILIDADE;

CREATE TABLE MANGA.TIPO -- Tabela adicional TIPO
(
ID INT PRIMARY KEY AUTO_INCREMENT,
 CAT VARCHAR (50) NOT NULL
);
INSERT INTO MANGA.TIPO (CAT) VALUE ('ARVORE');
INSERT INTO MANGA.TIPO (CAT) VALUE ('ARBUSTO');
INSERT INTO MANGA.TIPO (CAT) VALUE ('PALMEIRA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('FLOR');
INSERT INTO MANGA.TIPO (CAT) VALUE ('ORQUIDEA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('BROMELIA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('SUCULENTA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('CARNIVORA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('FOLHAGEM');
INSERT INTO MANGA.TIPO (CAT) VALUE ('GRAMADO');
INSERT INTO MANGA.TIPO (CAT) VALUE ('FORRACAO');
INSERT INTO MANGA.TIPO (CAT) VALUE ('AQUATICA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('HORTALICA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('TREPADEIRA');
INSERT INTO MANGA.TIPO (CAT) VALUE ('DANINHA');

SELECT * FROM MANGA.TIPO;

CREATE TABLE MANGA.SOLO -- Tabela adicional SOLO
(
ID INT PRIMARY KEY AUTO_INCREMENT,
 CAT VARCHAR (50) NOT NULL
);
INSERT INTO MANGA.SOLO (CAT) VALUE ('ARENOSO');
INSERT INTO MANGA.SOLO (CAT) VALUE ('ARGILOSO');
INSERT INTO MANGA.SOLO (CAT) VALUE ('HUMOSO');
INSERT INTO MANGA.SOLO (CAT) VALUE ('CALCARIO');
INSERT INTO MANGA.SOLO (CAT) VALUE ('SILTOSO');

SELECT * FROM MANGA.SOLO;

CREATE TABLE MANGA.CLIMA -- Tabela adicional CLIMA
(
ID INT PRIMARY KEY AUTO_INCREMENT,
 CAT VARCHAR (50) NOT NULL
);
INSERT INTO MANGA.CLIMA (CAT) VALUE ('ARIDO');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('SEMIARIDO');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('TEMPERADO');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('TROPICAL');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('EQUATORIAL');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('SUBTROPICAL');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('MEDITERRANEO');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('DESERTICO');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('POLAR');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('SUBPOLAR');
INSERT INTO MANGA.CLIMA (CAT) VALUE ('MONTANHA');

SELECT * FROM MANGA.CLIMA;

CREATE TABLE MANGA.PLANTA -- Tabela principal para referência
(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMECIE VARCHAR(100) UNIQUE NOT NULL,
 NOMEPOP VARCHAR(100) NOT NULL,
 UTI_ID INT,
FOREIGN KEY (UTI_ID) REFERENCES UTILIDADE(ID),
 TIPO_ID INT,
FOREIGN KEY (TIPO_ID) REFERENCES TIPO(ID),
 SOLO_ID INT,
FOREIGN KEY (SOLO_ID) REFERENCES SOLO(ID),
 TAM FLOAT NOT NULL,
 SOL FLOAT NOT NULL,
 CLIMA_ID INT,
FOREIGN KEY (CLIMA_ID) REFERENCES CLIMA(ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO MANGA.PLANTA (NOMECIE, NOMEPOP, UTI_ID, TIPO_ID, SOLO_ID, TAM, SOL, 
CLIMA_ID) VALUES ('TESTESTESTUS', 'TESTE', 1, 1, 1, 25.5, 5.5, 1);

SELECT * FROM MANGA.PLANTA;
-- Consulta para visualização dos dados FK
SELECT P.NOMECIE CIENTIFICO, P.NOMEPOP POPULAR, U.CAT UTILIDADADE, T.CAT TIPO, 
S.CAT SOLO, P.TAM TAMANHO, P.SOL SOL, C.CAT CLIMA
FROM MANGA.PLANTA P
INNER JOIN MANGA.UTILIDADE U ON U.ID = P.UTI_ID
INNER JOIN MANGA.TIPO T ON T.ID = P.TIPO_ID
INNER JOIN MANGA.SOLO S ON S.ID = P.SOLO_ID
INNER JOIN MANGA.CLIMA C ON C.ID = P.CLIMA_ID
;
CREATE TABLE MANGA.HERBARIO -- Tabela principal para Herbario
(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_CIE_ID VARCHAR(100),
FOREIGN KEY (NOME_CIE_ID) REFERENCES PLANTA(NOMECIE),
 APELIDO VARCHAR(100) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO MANGA.HERBARIO (NOME_CIE_ID, APELIDO) VALUES ('TESTESTESTUS', 'aMaisLindaDoJardim');

SELECT H.APELIDO, P.NOMEPOP, U.CAT 
FROM MANGA.HERBARIO H
INNER JOIN MANGA.PLANTA P ON P.NOMECIE = H.NOME_CIE_ID
INNER JOIN MANGA.UTILIDADE U ON U.ID = P.UTI_ID
;

CREATE TABLE MANGA.USUARIO -- Tabela para armazenamento de contas de usuário
(
ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_USUARIO INT,
    NOME VARCHAR(100),
    EMAIL VARCHAR (100),
    SENHA VARCHAR(25),
    DATANASCIMENTO DATE
);

-- Usuários de teste
-- TIPO_USUARIO: 1=Admin, 2=Autor, 3=Usuario
INSERT INTO MANGA.USUARIO (TIPO_USUARIO, NOME, EMAIL, SENHA, DATANASCIMENTO) VALUES 
(1, 'Administrador', 'admin@mangara.com', 'admin123', '1990-01-01'),
(2, 'Autor', 'autor@mangara.com', 'autor123', '1992-03-20'),
(3, 'Usuario Teste', 'usuario@mangara.com', 'user123', '1995-05-15');

CREATE TABLE MANGA.ARTIGO -- Tabela para armazenamento de artigos e notícias
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO TINYTEXT NOT NULL,
    SUBTITULO TINYTEXT,
    CORPO TEXT NOT NULL,
    AUTOR VARCHAR(100) NOT NULL,
    AUTOR_ID INT NOT NULL,
    FOREIGN KEY (AUTOR_ID) REFERENCES MANGA.USUARIO(ID), -- Tive que mudar tava dando inconsistencias 
    DATA DATE DEFAULT (CURRENT_DATE),
    REFERENCIAS TINYTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MANGA.HISTORICO_CONSULTA -- NOVA TABELA
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USU_ID INT,
    FOREIGN KEY (USU_ID) REFERENCES MANGA.USUARIO(ID),
    PLA_ID INT,
    FOREIGN KEY (PLA_ID) REFERENCES MANGA.PLANTA(ID),
    CONS_DATAHORA DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Criar CURTIDA -- NOVA TABELA
CREATE TABLE MANGA.CURTIDA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ARTIGO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    DATA_CURTIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ARTIGO_ID) REFERENCES ARTIGO(ID) ON DELETE CASCADE,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    UNIQUE KEY unique_curtida (ARTIGO_ID, USUARIO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Criar COMENTARIO -- NOVA TABELA
CREATE TABLE MANGA.COMENTARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ARTIGO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    CONTEUDO TEXT NOT NULL,  -- ✅ Mudou de COMENTARIO para CONTEUDO
    DATA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ARTIGO_ID) REFERENCES ARTIGO(ID) ON DELETE CASCADE,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;